= Исправление неполадок
:Author: Robonomics developers
:Revision: 0.1.0
:toc:
:sectnums:

== Транзакция долго висит как _pending_

Вероятнее всего, у транзакции указана очень низкая стоимость газа.

У провайдера есь ключ `--gasprice`, которая позволяет управлять стоимостью газа в ручном режиме. Посмотреть текущее состояние сети можно на странице https://etherscan.io/gasTracker[GasTracker].

Начиная с версии 0.5.4 можно указывать `--gasprice` в виде  `safe`, `fast`, `fastest`.

== До провайдера не доходят сообщения по IPFS

Во-первых, у провайдера и агента должны быть общие IPFS пиры

[source, bash]
----
ipfs swarm connect /dnsaddr/bootstrap.aira.life
----

Во-вторых, когда провайдер получает очередное сообщение, он отправляет служебное сообщение, которое можно получить через следующие топики

* `/liability/infochan/incoming/feedback/added_order` - если приянто Demand или Offer сообщение
* `/liability/infochan/incoming/feedback/added_pending_transaction` - если найдено два соответствующих сообщения и отправлена транзакция

== Сообщения обратной связи от провайдера

В топик `/liability/infochan/incoming/feedback/added_order` приходят сообщения при получении Demand или Offer

[source, json]
----
{
    "order": "0x...",
    "accepted": 0,
    "signature": "0x..."
}
----

Если найдены два соответствующих сообщения, провайдер отправляет хеш транзакции, который можно поймать в топике `/liability/infochan/incoming/feedback/added_pending_transaction`

[source, json]
----
{
    "tx": "0x..."
}
----

== Проблема, не вошедшая в список выше

Если проблема не описана выше, необходимо описать ошибку в этом https://github.com/airalab/robonomics-tools/issues[репозитории]

Настоятельно рекомендуется дать максимально полную информацию по ошибке: что делал, что ожидалось, что получил


